/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hugegraph_backend_store_kvt_KVTNative */

#ifndef _Included_org_apache_hugegraph_backend_store_kvt_KVTNative
#define _Included_org_apache_hugegraph_backend_store_kvt_KVTNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeInitialize
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeCreateTable
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeCreateTable
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeDropTable
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeDropTable
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeGetTableName
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeGetTableName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeGetTableId
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeGetTableId
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeListTables
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeListTables
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeStartTransaction
 * Signature: ()[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeStartTransaction
  (JNIEnv *, jclass);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeGet
 * Signature: (JJ[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeGet
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeSet
 * Signature: (JJ[B[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeSet
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeDel
 * Signature: (JJ[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeDel
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeScan
 * Signature: (JJ[B[BI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeScan
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jbyteArray, jint);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeBatchExecute
 * Signature: (J[I[J[[B[[B)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeBatchExecute
  (JNIEnv *, jclass, jlong, jintArray, jlongArray, jobjectArray, jobjectArray);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeCommitTransaction
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeCommitTransaction
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_apache_hugegraph_backend_store_kvt_KVTNative
 * Method:    nativeRollbackTransaction
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_hugegraph_backend_store_kvt_KVTNative_nativeRollbackTransaction
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
